Traceback (most recent call last):
  File "speedtest.py", line 105, in <module>
    _dict = collect_speeds(iters, mins)
  File "speedtest.py", line 62, in collect_speeds
    _dict = get_speedtest_json()
  File "speedtest.py", line 25, in get_speedtest_json
    _dict = json.loads(_json)
	
  File "C:\Users\sanch\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads 
	return _default_decoder.decode(s)
  File "C:\Users\sanch\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 340, in decode 
	raise JSONDecodeError("Extra data", s, end)
  
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 111)
